@Echo off

Set "ProfileSkin=%CD%\Profile Skin"
Set "MasterSkin=%CD%\Manage Profiles Skin"
Set "DVD2XboxSkin=%CD%\DVD2Xbox Skin"

Copy /Y "%ProfileSkin%\720p\Custom_Controls.xml"					"%MasterSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\Defaults.xml"							"%MasterSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\DialogBusy.xml"							"%MasterSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\DialogContextMenu.xml"					"%MasterSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\DialogGamepad.xml"						"%MasterSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\DialogKaiToast.xml"						"%MasterSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\DialogKeyboard.xml"						"%MasterSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\DialogMuteBug.xml"						"%MasterSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\DialogNetworkSetup.xml"					"%MasterSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\DialogNumeric.xml"						"%MasterSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\DialogOK.xml"							"%MasterSkin%\720p\"
::Copy /Y "%ProfileSkin%\720p\DialogProgress.xml"						"%MasterSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\DialogScriptInfo.xml"					"%MasterSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\DialogSeekBar.xml"						"%MasterSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\DialogSelect.xml"						"%MasterSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\DialogTextViewer.xml"					"%MasterSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\DialogVolumeBar.xml"					"%MasterSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\DialogYesNo.xml"						"%MasterSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\FileBrowser.xml"						"%MasterSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\FileManager.xml"						"%MasterSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\Font.xml"								"%MasterSkin%\720p\"
::Copy /Y "%ProfileSkin%\720p\Includes.xml"							"%MasterSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\Includes_Birthday.xml"					"%MasterSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\Includes_Debug.xml"						"%MasterSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\Includes_Easter.xml"					"%MasterSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\Includes_Snow.xml"						"%MasterSkin%\720p\"
::Copy /Y "%ProfileSkin%\720p\Includes_Variables.xml"					"%MasterSkin%\720p\"
::Copy /Y "%ProfileSkin%\720p\LockSettings.xml"						"%MasterSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\LoginScreen.xml"						"%MasterSkin%\720p\"
::Copy /Y "%ProfileSkin%\720p\MyPrograms.xml"							"%MasterSkin%\720p\"
::Copy /Y "%ProfileSkin%\720p\PlayerControls.xml"						"%MasterSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\Pointer.xml"							"%MasterSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\SettingsProfile.xml"					"%MasterSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\SettingsCategory.xml"					"%MasterSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\SettingsScreenCalibration.xml"			"%MasterSkin%\720p\"
Copy /Y "%ProfileSkin%\language\english\strings.po"					"%MasterSkin%\language\english\"
Copy /Y "%ProfileSkin%\Media\Textures.xpr"							"%MasterSkin%\Media\"

Copy /Y "%ProfileSkin%\720p\Custom_Controls.xml"					"%DVD2XboxSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\Defaults.xml"							"%DVD2XboxSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\DialogBusy.xml"							"%DVD2XboxSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\DialogContextMenu.xml"					"%DVD2XboxSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\DialogGamepad.xml"						"%DVD2XboxSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\DialogKaiToast.xml"						"%DVD2XboxSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\DialogKeyboard.xml"						"%DVD2XboxSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\DialogMuteBug.xml"						"%DVD2XboxSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\DialogNetworkSetup.xml"					"%DVD2XboxSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\DialogNumeric.xml"						"%DVD2XboxSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\DialogOK.xml"							"%DVD2XboxSkin%\720p\"
::Copy /Y "%ProfileSkin%\720p\DialogProgress.xml"						"%DVD2XboxSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\DialogScriptInfo.xml"					"%DVD2XboxSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\DialogSeekBar.xml"						"%DVD2XboxSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\DialogSelect.xml"						"%DVD2XboxSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\DialogTextViewer.xml"					"%DVD2XboxSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\DialogVolumeBar.xml"					"%DVD2XboxSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\DialogYesNo.xml"						"%DVD2XboxSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\FileBrowser.xml"						"%DVD2XboxSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\FileManager.xml"						"%DVD2XboxSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\Font.xml"								"%DVD2XboxSkin%\720p\"
::Copy /Y "%ProfileSkin%\720p\Includes.xml"							"%DVD2XboxSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\Includes_Birthday.xml"					"%DVD2XboxSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\Includes_Debug.xml"						"%DVD2XboxSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\Includes_Easter.xml"					"%DVD2XboxSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\Includes_Snow.xml"						"%DVD2XboxSkin%\720p\"
::Copy /Y "%ProfileSkin%\720p\Includes_Variables.xml"					"%DVD2XboxSkin%\720p\"
::Copy /Y "%ProfileSkin%\720p\LockSettings.xml"						"%DVD2XboxSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\LoginScreen.xml"						"%DVD2XboxSkin%\720p\"
::Copy /Y "%ProfileSkin%\720p\MyPrograms.xml"							"%DVD2XboxSkin%\720p\"
::Copy /Y "%ProfileSkin%\720p\PlayerControls.xml"						"%DVD2XboxSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\Pointer.xml"							"%DVD2XboxSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\SettingsProfile.xml"					"%DVD2XboxSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\SettingsCategory.xml"					"%DVD2XboxSkin%\720p\"
Copy /Y "%ProfileSkin%\720p\SettingsScreenCalibration.xml"			"%DVD2XboxSkin%\720p\"
Copy /Y "%ProfileSkin%\language\english\strings.po"					"%DVD2XboxSkin%\language\english\"
Copy /Y "%ProfileSkin%\Media\Textures.xpr"							"%DVD2XboxSkin%\Media\"

pause