@Echo off

Set "ProfileSkin=%CD%\Profile Skin"
Set "MasterSkin=%CD%\Manage Profiles Skin"
Set "DVD2XboxSkin=%CD%\DVD2Xbox Skin"

Copy /Y "%ProfileSkin%\colors\Defaults.xml"							"%MasterSkin%\colors\"
Copy /Y "%ProfileSkin%\xml\Defaults.xml"							"%MasterSkin%\xml\"
Copy /Y "%ProfileSkin%\xml\DialogBusy.xml"							"%MasterSkin%\xml\"
Copy /Y "%ProfileSkin%\xml\DialogContextMenu.xml"					"%MasterSkin%\xml\"
Copy /Y "%ProfileSkin%\xml\DialogGamepad.xml"						"%MasterSkin%\xml\"
Copy /Y "%ProfileSkin%\xml\DialogKaiToast.xml"						"%MasterSkin%\xml\"
Copy /Y "%ProfileSkin%\xml\DialogKeyboard.xml"						"%MasterSkin%\xml\"
Copy /Y "%ProfileSkin%\xml\DialogMuteBug.xml"						"%MasterSkin%\xml\"
Copy /Y "%ProfileSkin%\xml\DialogNetworkSetup.xml"					"%MasterSkin%\xml\"
Copy /Y "%ProfileSkin%\xml\DialogNumeric.xml"						"%MasterSkin%\xml\"
Copy /Y "%ProfileSkin%\xml\DialogOK.xml"							"%MasterSkin%\xml\"
Copy /Y "%ProfileSkin%\xml\DialogProgress.xml"						"%MasterSkin%\xml\"
Copy /Y "%ProfileSkin%\xml\DialogScriptInfo.xml"					"%MasterSkin%\xml\"
Copy /Y "%ProfileSkin%\xml\DialogSeekBar.xml"						"%MasterSkin%\xml\"
Copy /Y "%ProfileSkin%\xml\DialogSelect.xml"						"%MasterSkin%\xml\"
Copy /Y "%ProfileSkin%\xml\DialogTextViewer.xml"					"%MasterSkin%\xml\"
Copy /Y "%ProfileSkin%\xml\DialogVolumeBar.xml"						"%MasterSkin%\xml\"
Copy /Y "%ProfileSkin%\xml\DialogYesNo.xml"							"%MasterSkin%\xml\"
Copy /Y "%ProfileSkin%\xml\FileBrowser.xml"							"%MasterSkin%\xml\"
Copy /Y "%ProfileSkin%\xml\FileManager.xml"							"%MasterSkin%\xml\"
Copy /Y "%ProfileSkin%\xml\Font.xml"								"%MasterSkin%\xml\"
Copy /Y "%ProfileSkin%\xml\Includes_Context_Buttons.xml"			"%MasterSkin%\xml\"
Copy /Y "%ProfileSkin%\xml\Pointer.xml"								"%MasterSkin%\xml\"
Copy /Y "%ProfileSkin%\xml\SettingsCategory.xml"					"%MasterSkin%\xml\"
Copy /Y "%ProfileSkin%\xml\SettingsScreenCalibration.xml"			"%MasterSkin%\xml\"
Copy /Y "%ProfileSkin%\language\english\strings.po"					"%MasterSkin%\language\english\"
Copy /Y "%ProfileSkin%\Media\Textures.xpr"							"%MasterSkin%\Media\"